USE P2_BASES1
GO

CREATE PROCEDURE RegistrarEstudiante @carnet NUMERIC, @nombres VARCHAR(MAX), @apellidos VARCHAR(MAX), 
				@fecha_nacimiento DATE, @correo VARCHAR(MAX), @telefono NUMERIC, @direccion VARCHAR(MAX), @dpi BIGINT, @carrera VARCHAR(MAX)
AS
	BEGIN
		IF (SELECT dbo.F_VALIDAR_PALABRA(@nombres))= 0
			BEGIN 
				PRINT 'EL NOMBRE NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_PALABRA(@apellidos)) = 0
			BEGIN 
				PRINT 'EL APELLIDO NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_CORREO(@correo)) = 0
			BEGIN 
				PRINT 'EL CORREO NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_NUMERO(@telefono)) = 0
			BEGIN
				PRINT 'EL NUMERO DE TELEFONO NO ES VALIDO'
				RETURN
			END
		DECLARE @id_carrera AS NUMERIC = (SELECT dbo.F_GET_IDCARRERA(@carrera))
		IF (SELECT ISNULL(@id_carrera,-1)) = -1
			BEGIN
				PRINT 'LA CARRERA NO HA SIDO REGISTRADA'
				RETURN
			END
		DECLARE @carnet_val AS NUMERIC = (SELECT EST_ID FROM ESTUDIANTE WHERE EST_ID = @carnet)
		IF (SELECT ISNULL(@carnet_val,0)) = @carnet
			BEGIN
				PRINT 'EL ESTUDIANTE YA HA SIDO AGREGADO ANTERIORMENTE'
				RETURN
			END
		DECLARE @dpi_val AS BIGINT = (SELECT DPI FROM ESTUDIANTE WHERE DPI = @dpi)
		IF (SELECT ISNULL(@dpi_val,0)) = @dpi
			BEGIN
				PRINT 'EL DPI YA HA SIDO REGISTRADO ANTERIORMENTE'
				RETURN
			END
		INSERT INTO ESTUDIANTE(EST_ID, CARRERA_CAR_ID, NOMBRES, APELLIDOS, FECHA_NAC, CORREO, TELEFONO, DIRECCION, DPI)
				VALUES(@carnet, @id_carrera, @nombres, @apellidos, @fecha_nacimiento, @correo, @telefono, @direccion, @dpi)
		PRINT 'ESTUDIANTE REGISTRADO EXITOSAMENTE'
	END	
GO	
		

--DROP PROCEDURE RegistrarEstudiante
--SELECT * FROM ESTUDIANTE;

USE P2_BASES1
GO

CREATE PROCEDURE CrearCarrera @nombre VARCHAR(MAX)
AS
	BEGIN
		DECLARE @carr AS VARCHAR(MAX) = (SELECT NOMBRE FROM CARRERA WHERE NOMBRE = @nombre)
		IF (SELECT ISNULL(@carr,-1)) = @nombre
			BEGIN
				PRINT 'LA CARRERA YA HA SIDO REGISTRADA ANTERIORMENTE'
				RETURN
			END
		INSERT INTO CARRERA(NOMBRE) VALUES(@nombre)
		PRINT 'CARRERA REGISTRADA EXITOSAMENTE'
	END;
GO


--DROP PROCEDURE CrearCarrera
--SELECT * FROM CARRERA;


USE P2_BASES1
GO

CREATE PROCEDURE RegistrarDocente @siif NUMERIC, @nombres VARCHAR(MAX), @apellidos VARCHAR(MAX), 
				@fecha_nacimiento DATE, @correo VARCHAR(MAX), @telefono NUMERIC, @direccion VARCHAR(MAX), @dpi BIGINT
AS
	BEGIN
		IF (SELECT dbo.F_VALIDAR_PALABRA(@nombres))= 0
			BEGIN 
				PRINT 'EL NOMBRE NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_PALABRA(@apellidos)) = 0
			BEGIN 
				PRINT 'EL APELLIDO NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_CORREO(@correo)) = 0
			BEGIN 
				PRINT 'EL CORREO NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_NUMERO(@telefono)) = 0
			BEGIN
				PRINT 'EL NUMERO DE TELEFONO NO ES VALIDO'
				RETURN
			END
		DECLARE @carnet_val AS NUMERIC = (SELECT DOC_ID FROM DOCENTE WHERE DOC_ID = @siif)
		IF (SELECT ISNULL(@carnet_val,0)) = @siif
			BEGIN
				PRINT 'EL DOCENTE YA HA SIDO AGREGADO ANTERIORMENTE'
				RETURN
			END
		DECLARE @dpi_val AS BIGINT = (SELECT DPI FROM DOCENTE WHERE DPI = @dpi)
		IF (SELECT ISNULL(@dpi_val,0)) = @dpi
			BEGIN
				PRINT 'EL DPI YA HA SIDO REGISTRADO ANTERIORMENTE'
				RETURN
			END
		INSERT INTO DOCENTE(DOC_ID, NOMBRES, APELLIDOS, FECHA_NAC, CORREO, TELEFONO, DIRECCION, DPI)
				VALUES(@siif, @nombres, @apellidos, @fecha_nacimiento, @correo, @telefono, @direccion, @dpi)
		PRINT 'DOCENTE REGISTRADO EXITOSAMENTE'
	END	
GO	
		

--DROP PROCEDURE RegistrarDocente
--SELECT * FROM DOCENTE;


USE P2_BASES1
GO

CREATE PROCEDURE CrearCurso @codigo NUMERIC, @nombre VARCHAR(MAX), @cr_necesarios NUMERIC, @cr_otorga NUMERIC, @carrera VARCHAR(MAX), @obligatorio NUMERIC
AS
	BEGIN
		DECLARE @cod AS VARCHAR(MAX) = (SELECT CUR_ID FROM CURSO WHERE CUR_ID = @codigo)
		IF (SELECT ISNULL(@cod,-1)) = @codigo
			BEGIN
				PRINT 'EL CURSO YA HA SIDO REGISTRADO ANTERIORMENTE'
				RETURN
			END
		DECLARE @carr AS VARCHAR(MAX) = (SELECT CAR_ID FROM CARRERA WHERE NOMBRE = @carrera)
		IF (SELECT ISNULL(@carr,-1)) = -1
			BEGIN
				PRINT 'LA CARRERA NO HA SIDO REGISTRADA'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_NUMERO(@cr_necesarios)) = 0
			BEGIN
				PRINT 'EL NUMERO DE CREDITOS NECESARIOS NO ES VALIDO'
				RETURN
			END	
		IF (SELECT dbo.F_VALIDAR_NUMERO(@cr_otorga)) = 0
			BEGIN
				PRINT 'EL NUMERO DE CREDITOS QUE OTORGA NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_ESTADO(@obligatorio)) = 0
			BEGIN
				PRINT 'EL VALOR DE ESTADO (OBLIGATORIO/NO OBLIGATORIO) DEL CURSO ES INVALIDO'
				RETURN
			END
		INSERT INTO CURSO(CUR_ID, CARRERA_CAR_ID, NOMBRE, CR_NECESARIOS, CR_OTORGA, OBLIGATORIO) VALUES(@codigo, @carr, @nombre, @cr_necesarios, @cr_otorga, @obligatorio) 	
		PRINT 'CURSO AGREGADO EXITOSAMENTE'
	END;
GO


--DROP PROCEDURE CrearCurso
--SELECT * FROM CURSO;


USE P2_BASES1
GO

CREATE PROCEDURE HabilitarCurso @ciclo VARCHAR(MAX), @codigo NUMERIC, @siif NUMERIC, @seccion VARCHAR(MAX), @cupo NUMERIC
AS 
	BEGIN
		DECLARE @cod AS VARCHAR(MAX) = (SELECT CUR_ID FROM CURSO WHERE CUR_ID = @codigo)
		IF (SELECT ISNULL(@cod,-1)) = -1
			BEGIN
				PRINT 'EL CURSO NO HA SIDO REGISTRADO'
				RETURN
			END
		DECLARE @doc AS NUMERIC = (SELECT DOC_ID FROM DOCENTE WHERE DOC_ID = @siif)
		IF (SELECT ISNULL(@doc,-1)) = -1
			BEGIN
				PRINT 'EL DOCENTE NO HA SIDO REGISTRADO'
				RETURN
			END
		DECLARE @sec AS VARCHAR(MAX) = (SELECT SECCION FROM CURSO_HABILITADO WHERE SECCION = @seccion AND CURSO_CUR_ID = @codigo)
		IF (SELECT ISNULL(@sec,-1)) = @seccion OR (SELECT dbo.F_VALIDAR_CARACTER(@seccion)) = 0
			BEGIN
				PRINT 'LA SECCION YA HA SIDO REGISTRADA ANTERIORMENTE O INGRESE EL PARAMETRO CORRECTAMENTE'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_NUMERO(@cupo)) = 0
			BEGIN
				PRINT 'EL CUPO DE ESTUDIANTES NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_CICLO(@ciclo)) = 0
			BEGIN
				PRINT 'EL CICLO NO ES VALIDO'
				RETURN
			END
		INSERT INTO CURSO_HABILITADO(CICLO, CURSO_CUR_ID, DOCENTE_DOC_ID, SECCION, CUPO) VALUES(@ciclo, @codigo, @siif, @seccion, @cupo) 
		PRINT 'CURSO HABILITADO EXITOSAMENTE'
	END
GO

--DROP PROCEDURE HabilitarCurso
--SELECT * FROM CURSO_HABILITADO;

USE P2_BASES1
GO

CREATE PROCEDURE AgregarHorario @curso NUMERIC, @dia NUMERIC, @hora VARCHAR(MAX)
AS
	BEGIN
		DECLARE @cur1 AS NUMERIC = (SELECT CURH_ID FROM CURSO_HABILITADO WHERE CURH_ID = @curso)
			IF (SELECT ISNULL(@cur1,-1)) = -1 
				BEGIN
					PRINT 'EL CURSO INGRESADO NO HA SIDO HABILITADO'
					RETURN
				END
		DECLARE @cur AS NUMERIC = (SELECT CURSO_HABILITADO_CURH_ID FROM HORARIO WHERE CURSO_HABILITADO_CURH_ID = @curso)
		IF (SELECT ISNULL(@cur,-1)) = @curso OR (SELECT dbo.F_VALIDAR_NUMERO(@curso)) = 0
			BEGIN
				PRINT 'EL HORARIO DEL CURSO HABILITADO YA HA SIDO REGISTRADO ANTERIORMENTE O INGRESE EL PARAMETRO CORRECTAMENTE'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_DIA(@dia)) = 0
			BEGIN
				PRINT 'EL DIA INGRESADO NO ES VALIDO'
				RETURN
			END	
		IF (SELECT dbo.F_VALIDAR_HORARIO(@hora)) = 0
			BEGIN
				PRINT 'EL HORARIO INGRESADO NO ES VALIDO'
				RETURN
			END	
		INSERT INTO HORARIO(CURSO_HABILITADO_CURH_ID, DIA, HORARIO) VALUES(@curso, @dia, @hora)
		PRINT 'HORARIO ASIGNADO EXITOSAMENTE'
	END
GO


--DROP PROCEDURE AgregarHorario
--SELECT * FROM HORARIO;


USE P2_BASES1
GO

CREATE PROCEDURE AsignarCurso @codigo NUMERIC, @ciclo VARCHAR(MAX), @seccion VARCHAR(MAX), @carnet NUMERIC
AS
	BEGIN
		DECLARE @carr_cur AS NUMERIC = (SELECT CARRERA_CAR_ID FROM CURSO WHERE CUR_ID = @codigo)
		IF (SELECT ISNULL(@carr_cur, -1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR LA CARRERA DEL CURSO'
				RETURN
			END
		DECLARE @carr_est AS NUMERIC = (SELECT CARRERA_CAR_ID FROM ESTUDIANTE WHERE EST_ID = @carnet)
		IF (SELECT ISNULL(@carr_est, -1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR LA CARRERA DEL ESTUDIANTE'
				RETURN
			END
		IF @carr_cur != @carr_est AND @carr_cur != 0
			BEGIN
				PRINT 'ERROR AL ASIGNAR EL CURSO PORQUE NO ES DE LA CARRERA'
				RETURN
			END 
		DECLARE @cr_nec AS NUMERIC = (SELECT CR_NECESARIOS FROM CURSO WHERE CUR_ID = @codigo)
		IF (SELECT ISNULL(@cr_nec,-1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL NUMERO DE CREDITOS NECESARIOS DEL CURSO'
				RETURN
			END
		DECLARE @cr_est AS NUMERIC = (SELECT CREDITOS FROM ESTUDIANTE WHERE EST_ID = @carnet)
		IF (SELECT ISNULL(@cr_est, -1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL NUMERO DE CREDITOS QUE TIENE EL ESTUDIANTE'
				RETURN
			END
		IF @cr_est < @cr_nec
			BEGIN
				PRINT 'ERROR EN LA ASIGNACION, EL ESTUDIANTE NO POSEE LOS CREDITOS NECESARIOS PARA ASIGNARSE EL CURSO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_CICLO(@ciclo)) = 0
			BEGIN
				PRINT 'EL CICLO NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_CARACTER(@seccion)) = 0
			BEGIN
				PRINT 'LA SECCION NO ES VALIDA'
				RETURN
			END
		DECLARE @curh AS NUMERIC = (SELECT CURH_ID FROM CURSO_HABILITADO WHERE CURSO_CUR_ID = @codigo AND CICLO = @ciclo AND SECCION = @seccion)
		IF (SELECT ISNULL(@curh,-1)) = -1 
				BEGIN
					PRINT 'EL CURSO INGRESADO NO HA SIDO HABILITADO'
					RETURN
				END
		DECLARE @carnet_val AS NUMERIC = (SELECT EST_ID FROM ESTUDIANTE WHERE EST_ID = @carnet)
		IF (SELECT ISNULL(@carnet_val,0)) = 0
			BEGIN
				PRINT 'EL ESTUDIANTE NO HA SIDO AGREGADO'
				RETURN
			END
		DECLARE @asignados AS NUMERIC = (SELECT COUNT(*) FROM ASIGNACION WHERE CURSO_HABILITADO_CURH_ID = @curh)
		DECLARE @cup AS NUMERIC = (SELECT CUPO FROM CURSO_HABILITADO WHERE CURH_ID = @curh)
		IF (SELECT ISNULL(@asignados,-1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL NUMERO DE ESTUDIANTES ASIGNADOS'
				RETURN
			END
		IF (SELECT ISNULL(@cup, -1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL CUPO DE ESTUDIANTES PARA EL CURSO HABILITADO'
				RETURN
			END
		IF @asignados >= @cup
			BEGIN
				PRINT 'ERROR AL ASIGNAR EL CURSO, EL CUPO DEL CURSO HA LLEGADO A SU MAXIMO'
				RETURN
			END
		IF (SELECT ESTADO FROM ASIGNACION WHERE CURSO_HABILITADO_CURH_ID = @curh AND ESTUDIANTE_EST_ID = @carnet) = 1
			BEGIN
				PRINT 'ERROR AL ASIGNAR EL CURSO, EL CURSO YA FUE ASIGNADO ANTERIORMENTE'
				RETURN
			END
		IF (SELECT CURSO_CUR_ID FROM ASIGNACION 
			INNER JOIN CURSO_HABILITADO ON ASIGNACION.CURSO_HABILITADO_CURH_ID = CURSO_HABILITADO.CURH_ID 
			INNER JOIN ESTUDIANTE ON ASIGNACION.ESTUDIANTE_EST_ID = ESTUDIANTE.EST_ID  WHERE CURSO_HABILITADO.CURSO_CUR_ID = @codigo AND ESTUDIANTE.EST_ID = @carnet) = @codigo
			BEGIN
				PRINT 'ERROR AL ASIGNAR EL CURSO, EL CURSO YA FUE ASIGNADO NTERIORMENTE'
				RETURN
			END
		INSERT INTO ASIGNACION(CURSO_HABILITADO_CURH_ID, ESTUDIANTE_EST_ID) VALUES(@curh, @carnet)
		UPDATE CURSO_HABILITADO SET NUM_ASIGNADOS = @asignados + 1 WHERE CURH_ID = @curh
		PRINT 'ASIGNACION GENERADA EXITOSAMENTE'
			
	END
GO


--DROP PROCEDURE AsignarCurso
--SELECT * FROM ASIGNACION

USE P2_BASES1
GO

CREATE PROCEDURE DesasignarCurso @codigo NUMERIC, @ciclo VARCHAR(MAX), @seccion VARCHAR(MAX), @carnet NUMERIC
AS
	BEGIN
		IF (SELECT dbo.F_VALIDAR_CICLO(@ciclo)) = 0
			BEGIN
				PRINT 'EL CICLO NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_CARACTER(@seccion)) = 0
			BEGIN
				PRINT 'LA SECCION NO ES VALIDA'
				RETURN
			END
		DECLARE @curh AS NUMERIC = (SELECT CURH_ID FROM CURSO_HABILITADO WHERE CURSO_CUR_ID = @codigo AND CICLO = @ciclo AND SECCION = @seccion)
		IF (SELECT ISNULL(@curh,-1)) = -1 
				BEGIN
					PRINT 'EL CURSO INGRESADO NO HA SIDO HABILITADO'
					RETURN
				END
		DECLARE @carnet_val AS NUMERIC = (SELECT EST_ID FROM ESTUDIANTE WHERE EST_ID = @carnet)
		IF (SELECT ISNULL(@carnet_val,0)) = 0
			BEGIN
				PRINT 'EL ESTUDIANTE NO HA SIDO AGREGADO'
				RETURN
			END
		DECLARE @est AS NUMERIC = (SELECT ESTADO FROM ASIGNACION WHERE CURSO_HABILITADO_CURH_ID = @curh AND ESTUDIANTE_EST_ID = @carnet)
		IF (SELECT ISNULL(@est, -1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL ESTADO DEL CURSO'
				RETURN
			END
		IF @est = 0
			BEGIN
				PRINT 'EL CURSO SE ENCUENTRA EN ESTADO DESASIGNADO ACTUALMENTE'
				RETURN
			END
		DECLARE @nota AS NUMERIC = (SELECT NOTA FROM ASIGNACION WHERE CURSO_HABILITADO_CURH_ID = @curh AND ESTUDIANTE_EST_ID = @carnet)
		IF (SELECT ISNULL(@nota, -1)) != -1
			BEGIN
				PRINT 'ERROR AL DESASIGNAR EL CURSO, LA NOTA FINAL YA HA SIDO INGRESADA'
				RETURN
			END
		DECLARE @asignados AS NUMERIC = (SELECT COUNT(*) FROM ASIGNACION WHERE CURSO_HABILITADO_CURH_ID = @curh)
		IF (SELECT ISNULL(@asignados,-1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL NUMERO DE ESTUDIANTES ASIGNADOS'
				RETURN
			END
		UPDATE ASIGNACION SET ESTADO = 0 WHERE CURSO_HABILITADO_CURH_ID = @curh AND ESTUDIANTE_EST_ID = @carnet
		UPDATE CURSO_HABILITADO SET NUM_ASIGNADOS = @asignados - 1 WHERE CURH_ID = @curh
		PRINT 'CURSO DESASIGNADO EXITOSAMENTE' 
	END
GO


--DROP PROCEDURE DesasignarCurso
--SELECT * FROM ASIGNACION

USE P2_BASES1
GO

CREATE PROCEDURE IngresarNota @codigo NUMERIC, @ciclo VARCHAR(MAX), @seccion VARCHAR(MAX), @carnet NUMERIC, @nota NUMERIC
AS
	BEGIN
		IF (SELECT dbo.F_VALIDAR_CICLO(@ciclo)) = 0
			BEGIN
				PRINT 'EL CICLO NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_CARACTER(@seccion)) = 0
			BEGIN
				PRINT 'LA SECCION NO ES VALIDA'
				RETURN
			END
		DECLARE @curh AS NUMERIC = (SELECT CURH_ID FROM CURSO_HABILITADO WHERE CURSO_CUR_ID = @codigo AND CICLO = @ciclo AND SECCION = @seccion)
		IF (SELECT ISNULL(@curh,-1)) = -1 
				BEGIN
					PRINT 'EL CURSO INGRESADO NO HA SIDO HABILITADO'
					RETURN
				END
		DECLARE @carnet_val AS NUMERIC = (SELECT EST_ID FROM ESTUDIANTE WHERE EST_ID = @carnet)
		IF (SELECT ISNULL(@carnet_val,0)) = 0
			BEGIN
				PRINT 'EL ESTUDIANTE NO HA SIDO AGREGADO'
				RETURN
			END
		DECLARE @est AS NUMERIC = (SELECT ESTADO FROM ASIGNACION WHERE CURSO_HABILITADO_CURH_ID = @curh AND ESTUDIANTE_EST_ID = @carnet)
		IF (SELECT ISNULL(@est, -1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL ESTADO DEL CURSO'
				RETURN
			END
		IF @est = 0
			BEGIN
				PRINT 'EL CURSO SE ENCUENTRA EN ESTADO DESASIGNADO ACTUALMENTE'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_NUMERO(@nota)) = 0
			BEGIN
				PRINT 'LA NOTA INGRESADA NO ES VALIDA'
				RETURN
			END
		DECLARE @notas AS NUMERIC = (SELECT NOTA FROM ASIGNACION WHERE CURSO_HABILITADO_CURH_ID = @curh AND ESTUDIANTE_EST_ID = @carnet)
		IF (SELECT ISNULL(@notas, -1)) != -1
			BEGIN
				PRINT 'ERROR AL INGRESAR LA NOTA FINAL, YA HA SIDO INGRESADA ANTERIORMENTE'
				RETURN
			END
		DECLARE @cr_otorga AS NUMERIC = (SELECT CR_OTORGA FROM CURSO WHERE CUR_ID = @codigo)
		IF (SELECT ISNULL(@cr_otorga,-1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL NUMERO DE CREDITOS QUE OTORGA EL CURSO'
				RETURN
			END
		DECLARE @cr_est AS NUMERIC = (SELECT CREDITOS FROM ESTUDIANTE WHERE EST_ID = @carnet)
		IF (SELECT ISNULL(@cr_est, -1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL NUMERO DE CREDITOS QUE TIENE EL ESTUDIANTE'
				RETURN
			END
		IF ROUND(@nota,0) >= 61
			BEGIN
				UPDATE ESTUDIANTE SET CREDITOS = @cr_est + @cr_otorga WHERE EST_ID = @carnet
				PRINT 'CURSO APROBADO, LOS CREDITOS DEL ESTUDIANTE SE HAN ACTUALIZADO'
			END
		UPDATE ASIGNACION SET NOTA = ROUND(@nota,0) WHERE CURSO_HABILITADO_CURH_ID = @curh AND ESTUDIANTE_EST_ID = @carnet AND ESTADO = 1
		PRINT 'NOTA DEL CURSO AGREGADA EXITOSAMENTE' 
	END
GO


--DROP PROCEDURE IngresarNota
--SELECT * FROM ASIGNACION

USE P2_BASES1
GO

CREATE PROCEDURE GenerarActa @codigo NUMERIC, @ciclo VARCHAR(MAX), @seccion VARCHAR(MAX)
AS
	BEGIN
		IF (SELECT dbo.F_VALIDAR_CICLO(@ciclo)) = 0
			BEGIN
				PRINT 'EL CICLO NO ES VALIDO'
				RETURN
			END
		IF (SELECT dbo.F_VALIDAR_CARACTER(@seccion)) = 0
			BEGIN
				PRINT 'LA SECCION NO ES VALIDA'
				RETURN
			END
		DECLARE @curh AS NUMERIC = (SELECT CURH_ID FROM CURSO_HABILITADO WHERE CURSO_CUR_ID = @codigo AND CICLO = @ciclo AND SECCION = @seccion)
		IF (SELECT ISNULL(@curh,-1)) = -1 
				BEGIN
					PRINT 'EL CURSO INGRESADO NO HA SIDO HABILITADO'
					RETURN
				END
		DECLARE @calificados AS NUMERIC = (SELECT COUNT(*) FROM ASIGNACION 
											INNER JOIN CURSO_HABILITADO ON ASIGNACION.CURSO_HABILITADO_CURH_ID = CURSO_HABILITADO.CURH_ID 
											WHERE CURSO_HABILITADO_CURH_ID = @curh AND ESTADO = 1 AND CURSO_HABILITADO.AÑO = YEAR(GETDATE()) AND CURSO_HABILITADO.SECCION = @seccion AND NOTA = NULL )
		IF (SELECT ISNULL(@calificados, -1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR LA CANTIDAD DE ALUMNOS CALIFICADOS'
				RETURN
			END
		DECLARE @asignados AS NUMERIC = (SELECT NUM_ASIGNADOS FROM CURSO_HABILITADO WHERE CURH_ID = @curh)
		IF (SELECT ISNULL(@asignados,-1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL NUMERO DE ALUMNOS ASIGNADOS'
				RETURN
			END 
		PRINT @calificados
		PRINT @asignados
		IF @calificados != @asignados
			BEGIN
				PRINT 'NO SE PUEDEN GENERAR LAS ACTAS HASTA HABER INGRESADO NOTAS A TODOS LOS ESTUDIANTES'
				RETURN
			END
		IF @asignados = 0
			BEGIN
				PRINT 'ERROR AL GENERAR EL ACTA, NO HAY ESTUDIANTES ASIGNADOS AL CURSO'
				RETURN
			END
		INSERT INTO ACTA(ACT_DATE) VALUES(GETDATE())
		DECLARE @ultimo AS NUMERIC = (SELECT TOP 1 ACT_ID FROM ACTA ORDER BY ACT_ID DESC)
		IF (SELECT ISNULL(@ultimo, -1)) = -1
			BEGIN
				PRINT 'ERROR AL DETERMINAR EL ID DEL ACTA GENERADA'
				RETURN
			END
		UPDATE ASIGNACION SET ACTA_ACT_ID = @ultimo WHERE CURSO_HABILITADO_CURH_ID = @curh AND ESTADO = 1 AND NOTA != NULL
		PRINT 'ACTAS GENERADAS EXITOSAMENTE'
	END
GO


--DROP PROCEDURE GenerarActa
--SELECT * FROM ACTA