USE P2_BASES1
GO



CREATE TRIGGER TR_ACTA
ON ACTA FOR INSERT
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA ACTA', 'INSERT')
GO

CREATE TRIGGER TR_ASIGNACION1
ON ASIGNACION FOR INSERT
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA ASIGNACION', 'INSERT')
GO

CREATE TRIGGER TR_ASIGNACION2
ON ASIGNACION FOR UPDATE
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA ASIGNACION', 'UPDATE')
GO


CREATE TRIGGER TR_CARRERA
ON CARRERA FOR INSERT
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA CARRERA', 'INSERT')
GO

CREATE TRIGGER TR_CURSO
ON CURSO FOR INSERT
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA CURSO', 'INSERT')
GO

CREATE TRIGGER TR_CURSO_HABILITADO
ON CURSO_HABILITADO FOR INSERT
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA CURSO_HABILITADO', 'INSERT')
GO

CREATE TRIGGER TR_CURSO_HABILITADO2
ON CURSO_HABILITADO FOR UPDATE
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA CURSO_HABILITADO', 'UPDATE')
GO

CREATE TRIGGER TR_DOCENTE
ON DOCENTE FOR INSERT
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA DOCENTE', 'INSERT')
GO

CREATE TRIGGER TR_ESTUDIANTE
ON ESTUDIANTE FOR INSERT
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA ESTUDIANTE', 'INSERT')
GO

CREATE TRIGGER TR_HORARIO
ON HORARIO FOR INSERT
AS
INSERT INTO HISTORIAL(DESCRIPCION, TIPO) VALUES('SE REALIZO UNA ACCION EN LA TABLA HORARIO', 'INSERT')
GO